---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен быть доступен на различных устройствах.
non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Цена при переключении языка на "Russian", должна конвертироваться в рубли.